### PR TITLE
adding section about `watch`

### PR DESCRIPTION
**Pull request by hriprsd**
- solves #53 and #54

### CODE REVIEW

**Review by aerabi — COMMENTED** [review]
Great work! Could you perhaps put an example there as well, e.g. the one from [here](https://docs.docker.com/compose/how-tos/file-watch/):

```yaml
 services:
  web:
    build: .
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app/web
          ignore:
            - node_modules/
        - action: sync+restart
          path: ./proxy/nginx.conf
          target: /etc/nginx/conf.d/default.conf

  backend:
    build:
      context: backend
      target: builder
```

**Comment by hriprsd** [comment]
Please lemme know if any more  changes are needed. Thanks!

**Comment by hriprsd** [comment]
@aerabi there's some issue in pushing package post build. can u pls check?

**Comment by aerabi** [comment]
Sure, looking into it. 🙏

**Comment by hriprsd** [comment]
> Sure, looking into it. 🙏

Thank you! Hoping to get this counted towards my `hacktober`contributions. Hope you'll understand 🙂 

Thanks in advance ❤️

**Comment by hriprsd** [comment]
Please lemme know if i can help in any way 😸

**Review by aerabi — APPROVED** [review]
Great work! 🚀

**Pull request merged**
